version: '3'

services:
  nginx:
    image: hsxk/nginx:latest
    ports:
      - "80:80/tcp"
      - "80:80/udp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./log:/var/log/nginx
      - ./wordpress:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: bitnami/php-fpm:latest
    restart: always
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=80M
      - PHP_POST_MAX_SIZE=80M
    volumes:
      - ./wordpress:/var/www/html

  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: haokexin
      WORDPRESS_DB_PASSWORD: "localhost11"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "localhost11"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: haokexin
      MYSQL_PASSWORD: "localhost11"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "localhost11"
    depends_on:
      - mysql

volumes:
  mysql_data: